---
title: "chap3"
output: html_document
---
```{r data}
setwd("/Users//shota/git/StatisticalModeling/")
download.file("http://hosho.ees.hokudai.ac.jp/~kubo/stat/iwanamibook/fig/poisson/data3a.csv","data3.csv","curl")
d <- read.csv("data3.csv")
plot(d$x,d$y, pch = c(21,19)[d$f])
```

```{r exploratory}
library(ggplot2)
qplot(x,y = y,data = d, shape = f, colour = f)
qplot(x, y, data = d, geom = "boxplot", colour = f)
```

```{r fitting}
fit <- glm(y ~ x, data = d, family = poisson)
fit
summary(fit)
logLik(fit)
```

```{r prediction}
plot(d$x, d$y, pch = c(21,19)[d$f])
xx <- seq(min(d$x), max(d$x), length = 100)
lines(xx, exp(1.29 + 0.0757 * xx), lwd = 2)

yy <- predict(fit, newdata = data.frame(x = xx), type = "response")
lines(xx, yy, lwd = 2)
```

Assume that y is subject to f only, not x.

```{r fertilizer}
fit.f <- glm(y ~ f, data = d, family = poisson)
fit.f
summary(fit.f)
logLik(fit.f)
```

Asuume that y is affected by both x and f.

```{r model}
fit.all <- glm(y ~ x + f, data = d, family = poisson)
fit.all
summary(fit.all)
logLik(fit.all)
```
